//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASISTENCIA
    {
        [Display(Name = "Id Asistencia")]
        public int ID_ASIS { get; set; }
        [Display(Name = "Horario")]
        public int ID_HORARIO { get; set; }
        [Display(Name = "Estudiante")]
        public int ID_ESTUDIANTE { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime ASIS_FECHA { get; set; }
        [Display(Name = "Confirmado")]
        public string ASIS_CONF { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual HORARIO HORARIO { get; set; }
    }
}
