//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA
    {
        public int ID_NOTA { get; set; }
        public int ID_MATERIA { get; set; }
        public int ID_ESTUDIANTE { get; set; }
        public int ID_ANO { get; set; }
        public Nullable<float> NP1 { get; set; }
        public Nullable<float> NP2 { get; set; }
        public Nullable<float> NP3 { get; set; }
        public Nullable<float> EQ1 { get; set; }
        public Nullable<float> Q1 { get; set; }
        public Nullable<float> NP4 { get; set; }
        public Nullable<float> NP5 { get; set; }
        public Nullable<float> NP6 { get; set; }
        public Nullable<float> EQ2 { get; set; }
        public Nullable<float> Q2 { get; set; }
        public Nullable<float> FINAL { get; set; }
    
        public virtual ANO_LECTIVO ANO_LECTIVO { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
