//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROFESOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESOR()
        {
            this.MATERIA = new HashSet<MATERIA>();
        }

        [Display(Name = "Id Profesor")]
        public int ID_PROFESOR { get; set; }
        [Display(Name = "Usuario")]
        public string PROF_USU { get; set; }
        [Display(Name = "Tipo Usuario")]
        public int ID_TIPOU { get; set; }
        [Display(Name = "Nombre")]
        public string PROF_NOMBRE { get; set; }
        [Display(Name = "Apellido")]
        public string PROF_APELLIDO { get; set; }
        [Display(Name = "CI")]
        public string PROF_CEDULA { get; set; }
        [Display(Name = "Dirección")]
        public string PROF_DIRECCION { get; set; }
        [Display(Name = "Teléfono")]
        public string PROF_TELF { get; set; }
        [Display(Name = "Contraseña")]
        public string PROF_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIA> MATERIA { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
