//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class REPRESENTANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPRESENTANTE()
        {
            this.ESTUDIANTE = new HashSet<ESTUDIANTE>();
        }

        public int ID_REP { get; set; }


        [Display(Name = "USUARIO REP")]
        [StringLength(10, ErrorMessage =
            "El usuario debe ser de máximo 10 caracteres")]
        [RegularExpression(@"^[a-z]+$",
            ErrorMessage = "Coloque solo letras en minúscula porfavor")]
        [Required(ErrorMessage = "Campo Requerido")]
        public string REP_USU { get; set; }

        public int ID_TIPOU { get; set; }

        [Display(Name = "NOMBRE")]
        [StringLength(50, ErrorMessage = "El nombre debe ser de máximo 50 caracteres")]
        [RegularExpression(@"^[A-Z][a-zA-Z\s\u00C0-\u00FF]+$",
            ErrorMessage = "Coloque solo letras porfavor")]
        [Required(ErrorMessage = "Campo Requerido")]
        public string REP_NOMBRE { get; set; }



        [Display(Name = "APELLIDO")]
        [StringLength(50, ErrorMessage = "El apellido debe ser de máximo 50 caracteres")]
        [RegularExpression(@"^[A-Z][a-zA-Z\s\u00C0-\u00FF]+$",
           ErrorMessage = "Coloque solo letras porfavor")]
        [Required(ErrorMessage = "Campo Requerido")]
        public string REP_APELLIDO { get; set; }


        [Display(Name = "CÉDULA")]
        [Required(ErrorMessage = "Campo Requerido")]
        public string REP_CEDULA { get; set; }


        [Display(Name = "DIRECCIÓN")]
        [StringLength(255, ErrorMessage = "La dirección debe ser de máximo 255 caracteres")]
        [Required(ErrorMessage = "Campo Requerido")]
        public string REP_DIRECCION { get; set; }

        [Display(Name = "TELÉFONO CELULAR")]
        [StringLength(10, ErrorMessage =
            "El teléfono debe tener 10 dígitos")]
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression("^[0-9,$]*$",
            ErrorMessage = "Teléfono inválido")]
        public string REP_TELEFONO { get; set; }

        [Display(Name = "CONTRASEÑA")]
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$",
            ErrorMessage = "Contraseña: letra minúscula, mayúscula, un número y de logitud de 8")]
        public string REP_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTE> ESTUDIANTE { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
