
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prueba
{

using System;
    using System.Collections.Generic;
    
public partial class TIPO_USUARIO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPO_USUARIO()
    {

        this.ESTUDIANTE = new HashSet<ESTUDIANTE>();

        this.PROFESOR = new HashSet<PROFESOR>();

        this.REPRESENTANTE = new HashSet<REPRESENTANTE>();

    }


    public int ID_TIPOU { get; set; }

    public string TU_DESCRIP { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ESTUDIANTE> ESTUDIANTE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROFESOR> PROFESOR { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<REPRESENTANTE> REPRESENTANTE { get; set; }

}

}
