//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA
    {
        public int ID_ASIS { get; set; }
        public Nullable<int> ID_HORARIO { get; set; }
        public Nullable<int> ID_ESTUDIANTE { get; set; }
        public System.DateTime ASIS_FECHA { get; set; }
        public string ASIS_CONF { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual HORARIO HORARIO { get; set; }
    }
}
