//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPRESENTANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPRESENTANTE()
        {
            this.ESTUDIANTE = new HashSet<ESTUDIANTE>();
        }
    
        public int ID_REP { get; set; }
        public Nullable<int> ID_TIPOU { get; set; }
        public string REP_NOMBRE { get; set; }
        public string REP_APELLIDO { get; set; }
        public string REP_CEDULA { get; set; }
        public string REP_DIRECCION { get; set; }
        public int REP_TELEFONO { get; set; }
        public string REP_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTE> ESTUDIANTE { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
